export const idade = ['14', '16', '18'];
 
export const filmes = [{idade:14, título: "O Invocação do Mal", ano: "2013", gêneros: ["Terror/Mistério"], sinopse: "Os investigadores paranormais Ed e Lorraine Warren trabalham para ajudar a família aterrorizada por uma entidade demoníaca em sua fazenda.", imagem:  "/invocação.png" },
  {idade:14,título: "Annabelle", ano: "2014", gêneros: ["Terror/Mistério"], sinopse: "John Form acha que encontrou o presente ideal para sua esposa grávida, uma boneca vintage. No entanto, a alegria do casal não dura muito. Uma noite terrível, membros de uma seita satânica invadem a casa do casal em um ataque violento. Ao tentarem invocar um demônio, eles mancham a boneca de sangue, tornando-a receptora de uma entidade do mal..", imagem: "/Filme 2.jpg"},
  {idade:14,título: "Nosferatu", ano: "1922", gêneros: ["Terror/Fantasia "],sinopse: "O corretor de imóveis Hutter precisa vender um castelo cujo proprietário é o excêntrico conde Graf Orlock. O conde, na verdade, é um vampiro milenar que espalha o terror na região de Bremen, na Alemanha e se interessa por Ellen, a mulher de Hutter.", imagem: "/N.jpg"},
  {idade:14,título: "Corra!", ano: "2017", gêneros: [" Terror/Comédia"], sinopse: "Chris é um jovem fotógrafo negro que está prestes a conhecer os pais de Rose, sua namorada caucasiana. Na luxuosa propriedade dos pais dela, Chris percebe que a família esconde algo muito perturbador.", imagem: " /C.jpg" },
  {idade:16, título: "It - A Coisa", ano: "2017", gêneros: ["Terror/Mistério "], sinopse: "Um grupo de crianças se une para investigar o misterioso desaparecimento de vários jovens em sua cidade. Eles descobrem que o culpado é Pennywise, um palhaço cruel que se alimenta de seus medos e cuja violência teve origem há vários séculos.", imagem:"/it.jpg"},
  {idade:16, título: "Hereditário", ano: "2018", gêneros: ["Terror/Mistério "], sinopse: "Após a morte da reclusa avó, a família Graham começa a desvendar algumas coisas. Mesmo após a partida da matriarca, ela permanece como se fosse uma sombra sobre a família, especialmente sobre a solitária neta adolescente, Charlie, por quem ela sempre manteve uma fascinação não usual. Com um crescente terror tomando conta da casa, a família explora lugares mais escuros para escapar do infeliz destino que herdaram.", imagem: " /He.jpg"},
  {idade:18,título: "Terrifier", ano: "2016", gêneros: [" Terror/Slasher "], sinopse: "Enquanto cuida de duas crianças no halloween, uma babá encontra uma antiga fita VHS no saco de doces. O filme apresenta três contos de terror, todos ligados entre si por um palhaço assassino. Ao longo da noite, coisas estranhas começam a acontecer na casa e a presença do palhaço parece cada vez mais real.", imagem: "/t.jpg"} ];
